/**
* Payment service API
* Payment processing API  Note: The API is currently under development. Some endpoints do not yet have all the features described here, and the responses of some do not match the description here. 
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.ikioma.email.payment.api.spec

import fi.metatavu.ikioma.email.payment.spec.model.Error
import fi.metatavu.ikioma.email.payment.spec.model.SettlementIdItem

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class SettlementsApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty("org.openapitools.client.baseUrl", "https://api.checkout.fi")
        }
    }

    /**
    * List settlement IDs
    * Returns settlement IDs 
    * @param startDate Filter out settlements created before given date. (optional)
    * @param endDate Filter out settlements created after given date. (optional)
    * @param bankReference Only include settlements with the given bank reference (optional)
    * @param limit Limit the number of settlement IDs returned (optional)
    * @param submerchant Get submerchant&#39;s payment report (optional)
    * @param checkoutAccount Merchant ID (optional)
    * @param checkoutAlgorithm HMAC algorithm (optional)
    * @param checkoutMethod HTTP method of the request (optional)
    * @param checkoutTimestamp Current timestamp in ISO 8601 format (optional)
    * @param signature HMAC signature calculated over the request headers and payload (optional)
    * @return kotlin.collections.List<SettlementIdItem>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listSettlementIds(startDate: java.time.LocalDate?, endDate: java.time.LocalDate?, bankReference: kotlin.String?, limit: kotlin.Int?, submerchant: kotlin.Int?, checkoutAccount: kotlin.Int?, checkoutAlgorithm: kotlin.String?, checkoutMethod: kotlin.String?, checkoutTimestamp: java.time.OffsetDateTime?, signature: kotlin.String?) : kotlin.collections.List<SettlementIdItem> {
        val localVariableConfig = listSettlementIdsRequestConfig(startDate = startDate, endDate = endDate, bankReference = bankReference, limit = limit, submerchant = submerchant, checkoutAccount = checkoutAccount, checkoutAlgorithm = checkoutAlgorithm, checkoutMethod = checkoutMethod, checkoutTimestamp = checkoutTimestamp, signature = signature)

        val localVarResponse = request<kotlin.collections.List<SettlementIdItem>>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SettlementIdItem>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation listSettlementIds
    *
    * @param startDate Filter out settlements created before given date. (optional)
    * @param endDate Filter out settlements created after given date. (optional)
    * @param bankReference Only include settlements with the given bank reference (optional)
    * @param limit Limit the number of settlement IDs returned (optional)
    * @param submerchant Get submerchant&#39;s payment report (optional)
    * @param checkoutAccount Merchant ID (optional)
    * @param checkoutAlgorithm HMAC algorithm (optional)
    * @param checkoutMethod HTTP method of the request (optional)
    * @param checkoutTimestamp Current timestamp in ISO 8601 format (optional)
    * @param signature HMAC signature calculated over the request headers and payload (optional)
    * @return RequestConfig
    */
    fun listSettlementIdsRequestConfig(startDate: java.time.LocalDate?, endDate: java.time.LocalDate?, bankReference: kotlin.String?, limit: kotlin.Int?, submerchant: kotlin.Int?, checkoutAccount: kotlin.Int?, checkoutAlgorithm: kotlin.String?, checkoutMethod: kotlin.String?, checkoutTimestamp: java.time.OffsetDateTime?, signature: kotlin.String?) : RequestConfig {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, List<kotlin.String>>()
            .apply {
                if (startDate != null) {
                    put("startDate", listOf(parseDateToQueryString(startDate)))
                }
                if (endDate != null) {
                    put("endDate", listOf(parseDateToQueryString(endDate)))
                }
                if (bankReference != null) {
                    put("bankReference", listOf(bankReference.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        submerchant?.apply { localVariableHeaders["submerchant"] = this.toString() }
        checkoutAccount?.apply { localVariableHeaders["checkout-account"] = this.toString() }
        checkoutAlgorithm?.apply { localVariableHeaders["checkout-algorithm"] = this.toString() }
        checkoutMethod?.apply { localVariableHeaders["checkout-method"] = this.toString() }
        checkoutTimestamp?.apply { localVariableHeaders["checkout-timestamp"] = this.toString() }
        signature?.apply { localVariableHeaders["signature"] = this.toString() }
        
        val localVariableConfig = RequestConfig(
            method = RequestMethod.GET,
            path = "/settlements",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )

        return localVariableConfig
    }

}
