/**
* Payment service API
* Payment processing API  Note: The API is currently under development. Some endpoints do not yet have all the features described here, and the responses of some do not match the description here. 
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.ikioma.email.payment.spec.model


import com.squareup.moshi.Json

/**
 * 
 * @param status 
 * @param message Response details
 */

data class ActivateInvoiceResponse (
    @Json(name = "status")
    val status: ActivateInvoiceResponse.Status? = null,
    /* Response details */
    @Json(name = "message")
    val message: kotlin.String? = null
) {

    /**
     * 
     * Values: ok,error
     */
    enum class Status(val value: kotlin.String) {
        @Json(name = "ok") ok("ok"),
        @Json(name = "error") error("error");
    }
}

