/**
* Payment service API
* Payment processing API  Note: The API is currently under development. Some endpoints do not yet have all the features described here, and the responses of some do not match the description here. 
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.ikioma.email.payment.spec.model


import com.squareup.moshi.Json

/**
 * Add card form request
 * @param checkoutAccount Merchant ID
 * @param checkoutAlgorithm HMAC algorithm
 * @param checkoutRedirectSuccessUrl Merchant's url for user redirect on successful card addition
 * @param checkoutRedirectCancelUrl Merchant's url for user redirect on failed card addition
 * @param checkoutCallbackSuccessUrl Merchant's url called on successful card addition
 * @param checkoutCallbackCancelUrl Merchant's url called on failed card addition
 * @param language Alpha-2 language code for the card addition form
 */

data class AddCardFormRequest (
    /* Merchant ID */
    @Json(name = "checkout-account")
    val checkoutAccount: kotlin.Int,
    /* HMAC algorithm */
    @Json(name = "checkout-algorithm")
    val checkoutAlgorithm: AddCardFormRequest.CheckoutAlgorithm,
    /* Merchant's url for user redirect on successful card addition */
    @Json(name = "checkout-redirect-success-url")
    val checkoutRedirectSuccessUrl: kotlin.String,
    /* Merchant's url for user redirect on failed card addition */
    @Json(name = "checkout-redirect-cancel-url")
    val checkoutRedirectCancelUrl: kotlin.String,
    /* Merchant's url called on successful card addition */
    @Json(name = "checkout-callback-success-url")
    val checkoutCallbackSuccessUrl: kotlin.String? = null,
    /* Merchant's url called on failed card addition */
    @Json(name = "checkout-callback-cancel-url")
    val checkoutCallbackCancelUrl: kotlin.String? = null,
    /* Alpha-2 language code for the card addition form */
    @Json(name = "language")
    val language: AddCardFormRequest.Language? = null
) {

    /**
     * HMAC algorithm
     * Values: sha256,sha512
     */
    enum class CheckoutAlgorithm(val value: kotlin.String) {
        @Json(name = "sha256") sha256("sha256"),
        @Json(name = "sha512") sha512("sha512");
    }
    /**
     * Alpha-2 language code for the card addition form
     * Values: fI,sV,eN
     */
    enum class Language(val value: kotlin.String) {
        @Json(name = "FI") fI("FI"),
        @Json(name = "SV") sV("SV"),
        @Json(name = "EN") eN("EN");
    }
}

