/**
* Payment service API
* Payment processing API  Note: The API is currently under development. Some endpoints do not yet have all the features described here, and the responses of some do not match the description here. 
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.ikioma.email.payment.spec.model


import com.squareup.moshi.Json

/**
 * 
 * @param success URL to call when payment is succesfully paid. Can called multiple times; one must ensure idempotency of this endpoint. 
 * @param cancel URL to call when payment is cancelled and not fulfilled. Can called multiple times; one must ensure idempotency of this endpoint. 
 */

data class Callbacks (
    /* URL to call when payment is succesfully paid. Can called multiple times; one must ensure idempotency of this endpoint.  */
    @Json(name = "success")
    val success: kotlin.String,
    /* URL to call when payment is cancelled and not fulfilled. Can called multiple times; one must ensure idempotency of this endpoint.  */
    @Json(name = "cancel")
    val cancel: kotlin.String
)

