/**
* Payment service API
* Payment processing API  Note: The API is currently under development. Some endpoints do not yet have all the features described here, and the responses of some do not match the description here. 
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.ikioma.email.payment.spec.model


import com.squareup.moshi.Json

/**
 * 
 * @param countryCode e.g. FI
 * @param type Card type, for example ‘Visa’
 * @param partialPan Last four digits of the card
 * @param expireYear Card expiration year
 * @param expireMonth Card expiration month
 * @param cvcRequired Whether the CVC is required for paying with this card. Can be one of yes, no or not_tested.
 * @param bin First 2 or 6 digits of the card number. (6 MC/VISA, 2 Amex/Diners)
 * @param funding credit, debit or unknown
 * @param category business, prepaid or unknown
 * @param cardFingerprint Identifies a specific card number. Cards with the same PAN but different expiry dates will have the same PAN fingerprint. Hex string of length 64.
 * @param panFingerprint Identifies a specific card, including the expiry date. Hex string of length 64.
 */

data class Card (
    /* e.g. FI */
    @Json(name = "country_code")
    val countryCode: kotlin.String,
    /* Card type, for example ‘Visa’ */
    @Json(name = "type")
    val type: kotlin.String? = null,
    /* Last four digits of the card */
    @Json(name = "partial_pan")
    val partialPan: kotlin.String? = null,
    /* Card expiration year */
    @Json(name = "expire_year")
    val expireYear: kotlin.String? = null,
    /* Card expiration month */
    @Json(name = "expire_month")
    val expireMonth: kotlin.String? = null,
    /* Whether the CVC is required for paying with this card. Can be one of yes, no or not_tested. */
    @Json(name = "cvc_required")
    val cvcRequired: kotlin.String? = null,
    /* First 2 or 6 digits of the card number. (6 MC/VISA, 2 Amex/Diners) */
    @Json(name = "bin")
    val bin: kotlin.String? = null,
    /* credit, debit or unknown */
    @Json(name = "funding")
    val funding: kotlin.String? = null,
    /* business, prepaid or unknown */
    @Json(name = "category")
    val category: kotlin.String? = null,
    /* Identifies a specific card number. Cards with the same PAN but different expiry dates will have the same PAN fingerprint. Hex string of length 64. */
    @Json(name = "card_fingerprint")
    val cardFingerprint: kotlin.String? = null,
    /* Identifies a specific card, including the expiry date. Hex string of length 64. */
    @Json(name = "pan_fingerprint")
    val panFingerprint: kotlin.String? = null
)

