/**
* Payment service API
* Payment processing API  Note: The API is currently under development. Some endpoints do not yet have all the features described here, and the responses of some do not match the description here. 
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.ikioma.email.payment.spec.model


import com.squareup.moshi.Json

/**
 * 
 * @param status 
 * @param message Error description
 * @param meta Possible detailed error descriptions
 */

data class Error (
    @Json(name = "status")
    val status: Error.Status,
    /* Error description */
    @Json(name = "message")
    val message: kotlin.String,
    /* Possible detailed error descriptions */
    @Json(name = "meta")
    val meta: kotlin.collections.List<kotlin.String>? = null
) {

    /**
     * 
     * Values: error
     */
    enum class Status(val value: kotlin.String) {
        @Json(name = "error") error("error");
    }
}

