/**
* Payment service API
* Payment processing API  Note: The API is currently under development. Some endpoints do not yet have all the features described here, and the responses of some do not match the description here. 
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.ikioma.email.payment.spec.model

import fi.metatavu.ikioma.email.payment.spec.model.PaymentMethodGroupDataWithProviders
import fi.metatavu.ikioma.email.payment.spec.model.PaymentMethodProvider

import com.squareup.moshi.Json

/**
 * List grouped providers response body
 * @param terms Localized text with a link to payment terms
 * @param groups Payment method group data for all of groups that are included in the query
 * @param providers A flat list of payment method providers
 */

data class GroupedPaymentProvidersResponse (
    /* Localized text with a link to payment terms */
    @Json(name = "terms")
    val terms: kotlin.String,
    /* Payment method group data for all of groups that are included in the query */
    @Json(name = "groups")
    val groups: kotlin.collections.List<PaymentMethodGroupDataWithProviders>,
    /* A flat list of payment method providers */
    @Json(name = "providers")
    val providers: kotlin.collections.List<PaymentMethodProvider>
)

