/**
* Payment service API
* Payment processing API  Note: The API is currently under development. Some endpoints do not yet have all the features described here, and the responses of some do not match the description here. 
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.ikioma.email.payment.spec.model


import com.squareup.moshi.Json

/**
 * 
 * @param merchant Merchant who get's the commission money. This merchant id can not be deleted, has to be active and has to have same reseller with the merchant who initiated/created the webtrade. 
 * @param amount Commission amount in currency minor unit, eg. EUR cents. VAT not applicable. This field is needed only for specific shop-in-shop payments, usually not needed. 
 */

data class ItemCommission (
    /* Merchant who get's the commission money. This merchant id can not be deleted, has to be active and has to have same reseller with the merchant who initiated/created the webtrade.  */
    @Json(name = "merchant")
    val merchant: kotlin.String? = null,
    /* Commission amount in currency minor unit, eg. EUR cents. VAT not applicable. This field is needed only for specific shop-in-shop payments, usually not needed.  */
    @Json(name = "amount")
    val amount: kotlin.Int? = null
)

