/**
* Payment service API
* Payment processing API  Note: The API is currently under development. Some endpoints do not yet have all the features described here, and the responses of some do not match the description here. 
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.ikioma.email.payment.spec.model


import com.squareup.moshi.Json

/**
 * Payment report request
 * @param requestType In which format is the report delivered in
 * @param callbackUrl To which URL is the report delivered to
 * @param reportFields Limit the amount of fields included in the report. By default all fields are included.
 * @param submerchant Get submerchant's payment report
 */

data class PaymentReportBySettlementIdRequest (
    /* In which format is the report delivered in */
    @Json(name = "requestType")
    val requestType: PaymentReportBySettlementIdRequest.RequestType,
    /* To which URL is the report delivered to */
    @Json(name = "callbackUrl")
    val callbackUrl: kotlin.String,
    /* Limit the amount of fields included in the report. By default all fields are included. */
    @Json(name = "reportFields")
    val reportFields: kotlin.collections.List<PaymentReportBySettlementIdRequest.ReportFields>? = null,
    /* Get submerchant's payment report */
    @Json(name = "submerchant")
    val submerchant: kotlin.Int? = null
) {

    /**
     * In which format is the report delivered in
     * Values: json,csv
     */
    enum class RequestType(val value: kotlin.String) {
        @Json(name = "json") json("json"),
        @Json(name = "csv") csv("csv");
    }
    /**
     * Limit the amount of fields included in the report. By default all fields are included.
     * Values: entryDate,created,amount,status,firstname,familyname,description,reference,paymentMethod,stamp,address,postcode,postoffice,country,checkoutReference,archiveNumber,payerName,settlementId,settlementDate,originalTradeReference,vatPercentage,vatAmount,paymentMethodFee,paymentMethodCommission,shopInShopCommission,shopInShopCommissionVatPercentage,shopInShopCommissionVatAmount
     */
    enum class ReportFields(val value: kotlin.String) {
        @Json(name = "entryDate") entryDate("entryDate"),
        @Json(name = "created") created("created"),
        @Json(name = "amount") amount("amount"),
        @Json(name = "status") status("status"),
        @Json(name = "firstname") firstname("firstname"),
        @Json(name = "familyname") familyname("familyname"),
        @Json(name = "description") description("description"),
        @Json(name = "reference") reference("reference"),
        @Json(name = "paymentMethod") paymentMethod("paymentMethod"),
        @Json(name = "stamp") stamp("stamp"),
        @Json(name = "address") address("address"),
        @Json(name = "postcode") postcode("postcode"),
        @Json(name = "postoffice") postoffice("postoffice"),
        @Json(name = "country") country("country"),
        @Json(name = "checkoutReference") checkoutReference("checkoutReference"),
        @Json(name = "archiveNumber") archiveNumber("archiveNumber"),
        @Json(name = "payerName") payerName("payerName"),
        @Json(name = "settlementId") settlementId("settlementId"),
        @Json(name = "settlementDate") settlementDate("settlementDate"),
        @Json(name = "originalTradeReference") originalTradeReference("originalTradeReference"),
        @Json(name = "vatPercentage") vatPercentage("vatPercentage"),
        @Json(name = "vatAmount") vatAmount("vatAmount"),
        @Json(name = "paymentMethodFee") paymentMethodFee("paymentMethodFee"),
        @Json(name = "paymentMethodCommission") paymentMethodCommission("paymentMethodCommission"),
        @Json(name = "shopInShopCommission") shopInShopCommission("shopInShopCommission"),
        @Json(name = "shopInShopCommissionVatPercentage") shopInShopCommissionVatPercentage("shopInShopCommissionVatPercentage"),
        @Json(name = "shopInShopCommissionVatAmount") shopInShopCommissionVatAmount("shopInShopCommissionVatAmount");
    }
}

