/**
* Payment service API
* Payment processing API  Note: The API is currently under development. Some endpoints do not yet have all the features described here, and the responses of some do not match the description here. 
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.ikioma.email.payment.spec.model


import com.squareup.moshi.Json

/**
 * 
 * @param amount Amount to refund
 * @param stamp Original item stamp
 * @param refundStamp Merchant specific unique stamp for the refund
 * @param refundReference Merchant reference for the refund
 */

data class RefundItem (
    /* Amount to refund */
    @Json(name = "amount")
    val amount: kotlin.Long,
    /* Original item stamp */
    @Json(name = "stamp")
    val stamp: kotlin.String,
    /* Merchant specific unique stamp for the refund */
    @Json(name = "refundStamp")
    val refundStamp: kotlin.String? = null,
    /* Merchant reference for the refund */
    @Json(name = "refundReference")
    val refundReference: kotlin.String? = null
)

