/**
* Payment service API
* Payment processing API  Note: The API is currently under development. Some endpoints do not yet have all the features described here, and the responses of some do not match the description here. 
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.ikioma.email.payment.spec.model


import com.squareup.moshi.Json

/**
 * 
 * @param status 
 * @param transactionId Checkout transaction ID for the refund
 * @param provider Payment method provider
 */

data class RefundResponse (
    @Json(name = "status")
    val status: RefundResponse.Status? = null,
    /* Checkout transaction ID for the refund */
    @Json(name = "transactionId")
    val transactionId: java.util.UUID? = null,
    /* Payment method provider */
    @Json(name = "provider")
    val provider: kotlin.String? = null
) {

    /**
     * 
     * Values: ok,pending,fail
     */
    enum class Status(val value: kotlin.String) {
        @Json(name = "ok") ok("ok"),
        @Json(name = "pending") pending("pending"),
        @Json(name = "fail") fail("fail");
    }
}

