/**
* Payment service API
* Payment processing API  Note: The API is currently under development. Some endpoints do not yet have all the features described here, and the responses of some do not match the description here. 
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.ikioma.email.payment.spec.model


import com.squareup.moshi.Json

/**
 * 
 * @param networkAddress Customer IP address
 * @param countryCode Customer country code
 */

data class TokenCustomerDetails (
    /* Customer IP address */
    @Json(name = "network_address")
    val networkAddress: kotlin.String,
    /* Customer country code */
    @Json(name = "country_code")
    val countryCode: kotlin.String
)

