/**
* Payment service API
* Payment processing API  Note: The API is currently under development. Some endpoints do not yet have all the features described here, and the responses of some do not match the description here. 
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.ikioma.email.payment.spec.model

import fi.metatavu.ikioma.email.payment.spec.model.Card
import fi.metatavu.ikioma.email.payment.spec.model.TokenCustomerDetails

import com.squareup.moshi.Json

/**
 * 
 * @param token Token used to make authorization holds & charges on card
 * @param customer 
 * @param card 
 */

data class TokenizationRequestResponse (
    /* Token used to make authorization holds & charges on card */
    @Json(name = "token")
    val token: kotlin.String,
    @Json(name = "customer")
    val customer: TokenCustomerDetails? = null,
    @Json(name = "card")
    val card: Card? = null
)

